export const COFFEES = [
  {
    id: 'e4d6918b-b515-4bba-a7ef-4ad9fc9904fd',
    title: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    amount: 9.9,
    image: 'espresso.png',
    tags: ['Tradicional'],
  },
  {
    id: 'de36e171-5cbf-49ac-a0d9-997358a89967',
    title: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    amount: 9.9,
    image: 'american-coffee.png',
    tags: ['Tradicional'],
  },
  {
    id: '46e4aa47-6c58-4c46-b9d3-a3aae3ce66d5',
    title: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    amount: 9.9,
    image: 'creamy-espresso.png',
    tags: ['Tradicional'],
  },
  {
    id: 'ff8ce5a1-f88f-4987-b1f3-e7dc91edd6db',
    title: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    amount: 9.9,
    image: 'iced-coffee.png',
    tags: ['Tradicional', 'Gelado'],
  },
  {
    id: '372d433f-c6a4-4585-8338-c1f843e2ac3a',
    title: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    amount: 9.9,
    image: 'coffee-with-milk.png',
    tags: ['Tradicional', 'Com leite'],
  },
  {
    id: '3586cff3-a2e9-41d7-b142-683afa8266cb',
    title: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    amount: 9.9,
    image: 'latte.png',
    tags: ['Tradicional', 'Com leite'],
  },
  {
    id: '0c1764a0-bbf8-446e-af5c-d46fce62891e',
    title: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    amount: 9.9,
    image: 'capuccino.png',
    tags: ['Tradicional', 'Com leite'],
  },
  {
    id: 'e37e3aa7-c0cb-42d6-bc46-96892c87a6a2',
    title: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    amount: 9.9,
    image: 'macchiato.png',
    tags: ['Tradicional', 'Com leite'],
  },
  {
    id: 'c901f0ee-986e-44db-90d1-84b4dc3168d8',
    title: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    amount: 9.9,
    image: 'mochaccino.png',
    tags: ['Tradicional', 'Com leite'],
  },
  {
    id: '655e0fda-b291-488d-9c52-4c6cf8330fe4',
    title: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    amount: 9.9,
    image: 'hot-chocolate.png',
    tags: ['Especial', 'Com leite'],
  },
  {
    id: '7f79a7b1-ddd9-468f-98e8-5700a0df0bf6',
    title: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    amount: 9.9,
    image: 'cuban-coffee.png',
    tags: ['Especial', 'Alcoólico', 'Gelado'],
  },
  {
    id: '741b2abf-e510-4513-8bb0-c950a6a623da',
    title: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    amount: 9.9,
    image: 'hawaiian-coffee.png',
    tags: ['Especial'],
  },
]
